#!/bin/sh

#Remove anything after including and after the period
FILE=$( echo $1 | sed 's/\..*$//' )

GLADE="/usr/bin/glade-3"
GTK_BUILDER_CONVERT="/usr/bin/gtk-builder-convert"
ECHO="/bin/echo"
CAT="/bin/cat"
SED="/bin/sed"
TR="/bin/tr"

INPUT=${FILE}.glade
OUTPUT=${FILE}.xml
FINAL=${FILE}.c


${GLADE} ${INPUT} && \
${GTK_BUILDER_CONVERT} ${INPUT} ${OUTPUT}

#${ECHO} "char* ${FILE}_xml=\"" | tr -d '\n' > ${FINAL} &&
#${CAT} ${OUTPUT} | ${SED} -e 's/"/\\"/g' -e 's/$/\\n/g' | ${TR} -d '\n' >> ${FINAL} &&
#${ECHO} "\";" >> ${FINAL} &&

#${ECHO} "c file written"
#${ECHO} "done"
